News/urls.py
from django.contrib import admin
from django.urls import path


from News import views
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newsfeed.urls')),
    path('account/', include('login.urls')),
    
]

login/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from django.urls import include, path

app_name = 'login'
urlpatterns = [
    path('login/', views.login_page, name="loginhome"),
    path('signup/', views.sign_up, name="signuphome"),
    path('profile/', views.profile, name="profile"),
    path('logout/',views.logout_user,name="logout"),
    
]

newsfeed/urls.py
from django.contrib import admin
from django.urls import path


from newsfeed import views
from django.urls import include, path
from django.conf.urls import url

app_name = 'newsfeed'

urlpatterns = [

    path('technology/', views.technology, name="tech"),
    path('lifestyle/', views.lifestyle, name="life"),
    path('sports/', views.sports, name="sport"),
    path('', views.base, name="base"),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')
    #marked_news = ArrayField( models.CharField(max_length=100, blank=True),size=10)


    

newsfeed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class savedpost(models.Model):
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile')
    #marked_news = ArrayField( models.CharField(max_length=100, blank=True),size=10)

xyz/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

News/views.py
from django.shortcuts import render

# Create your views here.
from bs4 import BeautifulSoup
import requests











#print(Sport)

login/views.py
# Create your views here.
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from login.forms import SignUpForm

# Create your views here.

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered }
    return render(request, 'app_login/signup.html',context=dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('newsfeed:base'))

    return render(request,'app_login/login.html', context={'form':form})

@login_required
def profile(request):
    return render(request, 'app_login/profile.html')

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('newsfeed:base'))

newsfeed/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from bs4 import BeautifulSoup
import requests


def base(request):
    return render(request,'base.html')


class news_object:
  def __init__(self):
    self.text = ""
    self.link = ""
    self.source=""



def technology(request):

    Techpage = requests.get('https://www.indiatoday.in/technology')
    soup= BeautifulSoup(Techpage.content,'lxml')
    Techheadings= soup.findAll('ul',class_='itg-listing')
    technology =[]
    technologylinks=[]
    for x in Techheadings:
       for y in x:
          tech=news_object()
          tech.text=y.text
          tech.link="https://indiatoday.in"+y.a['href']
          tech.source="India Today"
          technology.append(tech)
    return render(request, 'tech.html', {'technology': technology})

def lifestyle(request):
    Lifepage = requests.get('https://www.indiatoday.in/lifestyle')
    soup= BeautifulSoup(Lifepage.content,'lxml')
    Lifeheadings= soup.findAll('ul',class_='itg-listing')
    lifestyle=[]
    for x in Lifeheadings:
        for y in x:
            life=news_object()
            life.text=y.text
            life.link="https://indiatoday.in"+y.a['href']
            life.source="India Today"
            lifestyle.append(life)
    return render(request, 'lifestyle.html', {'lifestyle': lifestyle})

def sports(request):
    Sportpage = requests.get('https://www.indiatoday.in/sports')
    soup= BeautifulSoup(Sportpage.content,'lxml')
    sportheadings= soup.findAll('ul',class_='itg-listing')
    hSportpage = requests.get('https://www.thehindu.com/sport/')
    hsoup= BeautifulSoup(hSportpage.content,'lxml')
    hsportheadings= hsoup.findAll('h3')
    hsports=[]
    for x in hsportheadings[:17]:
            sport=news_object()
            sport.text=x.text
            sport.link='https://www.thehindu.com/sport/'
            sport.source="The Hindu"
            hsports.append(sport)
    
    sports=[]
   
    for x in sportheadings:
        for y in x:
            sport=news_object()
            sport.text=y.text
            sport.link="https://indiatoday.in"+y.a['href']
            sport.source="India Today"
            sports.append(sport)
    sname="India Today"
    sports+=hsports
    
    return render(request, 'sports.html', {'sports': sports,'IndiaToday':sname})

xyz/views.py
from django.shortcuts import render

# Create your views here.

templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title%} Login Form {% endblock %}
{% block body_block %}
    <div class="login-box">
      <h2>Login form</h2>
      <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm" >Login</button>
      </form>

    </div>
{% endblock %}

templates/app_login/profile.html
{% extends 'base.html' %}
{% block title %} Profile Page  {% endblock %}


{% block body_block %}
<h2 style="margin-left: 50px;">Your Profile </h2>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="250px" height="250px">
<br><br>
<a href="{% url 'login:loginhome' %}" class="btn btn-info btn-sm">Change Profile Pic</a>


{% else %}
<img src="/media/download.jpg" class="rounded-circle" width="350px" height="250px">
<br>
<a href="{% url 'login:loginhome' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
{% endif %}


<p>Username : {{ user.username }}</p>
<p>Email : {{ user.email }}</p>
<p>Name : {{ user.first_name }} {{ user.last_name }}</p>

<br>
<a href="{% url 'login:loginhome' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title%}Sign Up Page{% endblock %}
{% block body_block %}
    <div class="signup-box">
      <h2>Signup form</h2>
      <form method="post">
        {{ form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm" >Sign Up</button>
      </form>

    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
<a href="http://free-website-translation.com/" id="ftwtranslation_button" hreflang="en" title="" style="border:0;">
  <img src="http://free-website-translation.com/img/fwt_button_en.gif" id="ftwtranslation_image" alt="website translator plugin" style="border:0;"/>
</a> <script type="text/javascript" src="http://free-website-translation.com/scripts/fwt.js" /></script>

    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'newsfeed:base' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsfeed:tech'%}">Technology</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsfeed:sport'%}">Sports</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newsfeed:life'%}">Lifestyle</a>
            </li>
            {%if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:logout'%}">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:loginhome'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:signuphome'%}">Sign Up</a>
            </li>
            {%endif%}
          </ul>
        </div>
      </nav>
      <div class="container" style="padding-top: 20px">
        {% block body_block %}


        {% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>

</html>

templates/lifestyle.html
{% extends 'base.html' %}
{% block title%} lifestyle {% endblock %}
{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                    <h3 class="text-centre"> Lifestyle</h3>
                   {% for n in lifestyle %}
                    <h5> -<a href="{{n.link}}">{{ n.text }} </a>  </h5>
                        <p> {{n.source}}</p>
                    {% endfor %}
                    <br>
            </div>
        </div>
</div>
{% endblock %}

templates/sports.html
{% extends 'base.html' %}
{% block title%} lifestyle {% endblock %}
{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="col-6" style="width: 50px;">
                    <h3 class="text-centre"> Sports</h3>
                    {% for n in sports %}
                    
                    {% if n.source == IndiaToday %}
                    <h5 style="text-align:left;"> - <a href="{{n.link}}"> {{n.text}} </a>  </h5>
                    <p style="text-align:left;">{{n.source}}</p>
                    <hr>
                    {%else%}
                    {% endif%}
                  
                    {% endfor %}
                   
            </div>
            <div class="col-6" style="padding-left:100px;">
                <h3 class="text-centre"> Sports</h3>
                {% for n in sports %}
                
                {% if n.source != IndiaToday %}
                <h5 style="text-align:left;"> - <a href="#"> {{n.text}} </a>  </h5>
                <p style="text-align:left;">{{n.source}}</p>
                <hr>
                {%else%}
                
                {% endif%}
               
                {% endfor %}
                
                <br>
        </div>
        </div>
</div>
{% endblock %}

templates/tech.html
{% extends 'base.html' %}
{% block title%} lifestyle {% endblock %}
{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                    <h3 class="text-centre"> Technology</h3>
                    {% for n in technology %}
                  <a href="{{n.link}}"> <h5> -  {{n.text}} </h5> </a>
                  <p> {{n.source}}</p>
                    <hr>
                    {% endfor %}
                    <br>
            </div>
        </div>
</div>
{% endblock %}